config/routes.rb
Rails.application.routes.draw do
  resources :discussions
  resources :forums
  resources :posts
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/me', to: 'users#showMe', as: 'my_profile'
  get 'users/:id', to: 'users#show'
  root to: 'home#landing'
  get 'home/landing'
  get 'home/home'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<div class="<%= if notice then 'absolute-flash-active' else 'absolute-flash' end%>">
  <p class="notice"><%= notice %></p>
</div>
<div class="<%= if alert then 'absolute-flash-active' else 'absolute-flash' end%>">
  <p class="alert"><%= alert %></p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Website Logo', root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <%= link_to 'Home', home_home_path, class: 'navbar-brand' %>
      <%= link_to 'About us', home_about_path, class: 'navbar-brand' %>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Forums
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <!-- Post Links go here -->
          <li><%= link_to 'Forums', forums_path %></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Profile
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <!-- Profile links go here -->
          <% if user_signed_in? %>
            <li>Welcome back <%= current_user.first_name%></li>
            <li><%= link_to 'Profile', my_profile_path %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => 'DELETE' %></li>
          <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Profile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/flash_messages' %>
  </body>
</html>